spring:
  application:
    name: tlias-web-management
#    配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: luotovo
    password: Lt586826@
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大总上传限制
      max-request-size: 100MB
#    mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    bucketName: java-luot
    region: cn-beijing
    endpoint: oss-cn-beijing.aliyuncs.com

server:
  port: 8082
